openapi: 3.1.1
info:
  title: Calorie Counter API
  description: API for managing physical activities and calorie tracking.
  version: v1.0.0
  contact:
    name: Alejandro Granados
    email: alejandro.magb@gmail.com
    url: https://github.com/aledelorbe

servers:
  - url: http://localhost:7000
    description: Local server

tags:
  - name: Activities
    description: Endpoints related to manage the activities

paths:
  /api/activities:
    get:
      tags:
        - Activities
      summary: Get all activities
      description: Returns a list of all stored activities.
      responses:
        '200':
          description: List of activities retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Activity'
    post:
      tags:
        - Activities
      summary: Create a new activity
      description: Creates a new activity record.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityInput'
      responses:
        '201':
          description: Activity created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        '400':
          description: Validation error.

    delete:
      tags:
        - Activities
      summary: Delete all activities
      description: Deletes all registered activities.
      responses:
        '200':
          description: All activities deleted successfully.

  /api/activities/{id}:
      get:
        tags:
          - Activities
        summary: Get an activity by ID
        description: Retrieves a specific activity by its unique ID.
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
            description: Activity ID
        responses:
          '200':
            description: Activity found.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Activity'
          '404':
            description: Activity not found.
      put:
        tags:
          - Activities
        summary: Update an existing activity
        description: Updates all fields of a specific activity by ID.
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
            description: Activity ID
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        responses:
          '201':
            description: Activity updated successfully.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Activity'
          '400':
            description: Validation error.
          '404':
            description: Activity not found.
      delete:
        tags:
          - Activities
        summary: Delete an activity by ID
        description: Deletes a specific activity by its ID.
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
            description: Activity ID
        responses:
          '200':
            description: Activity deleted successfully.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Activity'
          '404':
            description: Activity not found.

components:
  schemas:
    Activity:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier of the activity.
        category:
          type: string
          description: Activity category (e.g., cardio, strength, etc.).
        name:
          type: string
          description: Name of the activity.
        calories:
          type: integer
          format: int32
          minimum: 1
          description: Calories burned by performing the activity.
      required:
        - category
        - name
        - calories

    ActivityInput:
      type: object
      properties:
        category:
          type: string
          description: Activity category (e.g., cardio, strength, etc.).
        name:
          type: string
          description: Name of the activity.
        calories:
          type: integer
          format: int32
          minimum: 1
          description: Calories burned by performing the activity.
      required:
        - category
        - name
        - calories

